config/routes.rb
Rails.application.routes.draw do

  get 'last/cpmodes'

	get 'cpoints/last_modes' => 'cpoints#last_modes'

  resources :cpoints do
					resources :cpmodes
  end

	namespace :last do
		resources :cpmodes
	end
end

app/models/cpmode.rb
class Cpmode < ActiveRecord::Base
  belongs_to :cpoint
end

app/controllers/cpmodes_controller.rb
class CpmodesController < ApplicationController
  before_action :set_cpmode, only: [:show, :edit, :update, :destroy]

  # GET /cpmodes
  # GET /cpmodes.json
  def index
    @cpoint = Cpoint.find(params[:cpoint_id])
    @cpmodes = @cpoint.cpmodes
  end

  # GET /cpmodes/1
  # GET /cpmodes/1.json
  def show
  end

  # GET /cpmodes/new
  def new
    @cpoint = Cpoint.find(params[:cpoint_id])
    @cpmode = @cpoint.cpmodes.build
  end

  # GET /cpmodes/1/edit
  def edit
  end

  # POST /cpmodes
  # POST /cpmodes.json
  def create
    @cpoint = Cpoint.find(params[:cpoint_id])
    @cpmode = @cpoint.cpmodes.build(cpmode_params)

    respond_to do |format|
      if @cpmode.save
				write_cp_mode_image()

        format.html { redirect_to cpoint_cpmodes_path( @cpoint ), notice: 'Cpmode was successfully created.' }
        format.json { render :show, status: :created, location: @cpmode }
      else
        format.html { render :new }
        format.json { render json: @cpmode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cpmodes/1
  # PATCH/PUT /cpmodes/1.json
  def update
  	
    @cpoint = Cpoint.find(params[:cpoint_id])

    respond_to do |format|
      if @cpmode.update(cpmode_params)
				write_cp_mode_image()

        format.html { redirect_to cpoint_cpmodes_path( @cpoint ), notice: 'Cpmode was successfully updated.' }
        format.json { render :show, status: :ok, location: @cpmode }
      else
        format.html { render :edit }
        format.json { render json: @cpmode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cpmodes/1
  # DELETE /cpmodes/1.json
  def destroy
    @cpmode.destroy
    respond_to do |format|
      format.html { redirect_to cpoint_cpmodes_path(@cpoint), notice: 'Cpmode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
	
	MIN_VAL = 0
	MAX_VAL = 8

  private
		def write_cp_mode_image()
			canvas = Magick::ImageList.new
			image = canvas.new_image( 200, 200 ){ self.background_color = 'white' }

			yellow_angle_start = 135
			yellow_angle_end = yellow_angle_start + 270*@cpmode.value_min/MAX_VAL
			green_angle_end = yellow_angle_end + 270*(@cpmode.value_max - @cpmode.value_min)/MAX_VAL

			circle = Magick::Draw.new
			circle.stroke('red')
			circle.fill_opacity(0)
			circle.stroke_width(5)
			circle.ellipse( canvas.rows/2, canvas.columns/2, 73, 73, green_angle_end, 59 )
			circle.draw( canvas )

			circle = Magick::Draw.new
			circle.stroke('green')
			circle.fill_opacity(0)
			circle.stroke_width(5)
			circle.ellipse( canvas.rows/2, canvas.columns/2, 73, 73, yellow_angle_end, green_angle_end)
			circle.draw( canvas )

			circle = Magick::Draw.new
			circle.stroke('yellow')
			circle.fill_opacity(0)
			circle.stroke_width(5)
			circle.ellipse( canvas.rows/2, canvas.columns/2, 73, 73, yellow_angle_start, yellow_angle_end)
			circle.draw( canvas )

			circle = Magick::Draw.new
			circle.stroke('black')
			circle.fill_opacity(0)
			circle.stroke_width(1)
			circle.ellipse( canvas.rows/2, canvas.columns/2, 76, 76, 0, 360 )
			circle.draw( canvas )

			circle = Magick::Draw.new
			circle.stroke('black')
			circle.fill_opacity(0)
			circle.stroke_width(1)
			circle.ellipse( canvas.rows/2, canvas.columns/2, 70, 70, 0, 360 )
			circle.draw( canvas )

				txt = Magick::Draw.new

				image.annotate(txt, 0,0,55,150, "0"){
								txt.gravity = Magick::ForgetGravity
								txt.pointsize = 15
								txt.stroke = '#000000'
								txt.fill = '#000000'
				}

				txt = Magick::Draw.new

				image.annotate(txt, 0,0,35,115, "1"){
								txt.gravity = Magick::ForgetGravity
								txt.pointsize = 15
								txt.stroke = '#000000'
								txt.fill = '#000000'
				}

				txt = Magick::Draw.new

				image.annotate(txt, 0,0,40,80, "2"){
								txt.gravity = Magick::ForgetGravity
								txt.pointsize = 15
								txt.stroke = '#000000'
								txt.fill = '#000000'
				}

				txt = Magick::Draw.new

				image.annotate(txt, 0,0,60,55, "3"){
								txt.gravity = Magick::ForgetGravity
								txt.pointsize = 15
								txt.stroke = '#000000'
								txt.fill = '#000000'
				}

				txt = Magick::Draw.new

				image.annotate(txt, 0,0,95,45, "4"){
								txt.gravity = Magick::ForgetGravity
								txt.pointsize = 15
								txt.stroke = '#000000'
								txt.fill = '#000000'
				}

				txt = Magick::Draw.new

				image.annotate(txt, 0,0,130,55, "5"){
								txt.gravity = Magick::ForgetGravity
								txt.pointsize = 15
								txt.stroke = '#000000'
								txt.fill = '#000000'
				}

				txt = Magick::Draw.new

				image.annotate(txt, 0,0,155,85, "6"){
								txt.gravity = Magick::ForgetGravity
								txt.pointsize = 15
								txt.stroke = '#000000'
								txt.fill = '#000000'
				}

				txt = Magick::Draw.new

				image.annotate(txt, 0,0,155,120, "7"){
								txt.gravity = Magick::ForgetGravity
								txt.pointsize = 15
								txt.stroke = '#000000'
								txt.fill = '#000000'
				}

				txt = Magick::Draw.new

				image.annotate(txt, 0,0,135,150, "8"){
								txt.gravity = Magick::ForgetGravity
								txt.pointsize = 15
								txt.stroke = '#000000'
								txt.fill = '#000000'
				}

				txt = Magick::Draw.new

				image.annotate(txt, 0,0,45,110, "#{@cpmode.value_min} - #{@cpmode.value_max}"){
								txt.gravity = Magick::ForgetGravity
								txt.pointsize = 30 
								txt.stroke = '#0000FF'
								txt.fill = '#0000FF'
				}

			canvas.write( 'public/' + (  @cpoint.image ) )
		end

    # Use callbacks to share common setup or constraints between actions.
    def set_cpmode
    	@cpoint = Cpoint.find(params[:cpoint_id])
     	@cpmode = Cpmode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cpmode_params
      params.require(:cpmode).permit(:cpoint_id, :date_reg, :value_min, :value_max)
    end
end

app/helpers/cpmodes_helper.rb
module CpmodesHelper
end

app/views/cpmodes/_form.html.erb
<script language="JavaScript">
$(function(){
	$('#sl_min').change(function(){
		$form = $(this);
		$input_value = $('#sl_min').val();
		$('#sl_min_val').val($input_value);
	});

	$('#sl_max').change(function(){
		$form = $(this);
		$input_value = $('#sl_max').val();
		console.log($input_value);
		$('#sl_max_val').val($input_value);
	});

	$('#sl_min').change();
	$('#sl_max').change();
});
</script>
<div class="container">
<%= form_for([@cpoint,@cpmode]) do |f| %>
  <% if @cpmode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cpmode.errors.count, "error") %> prohibited this cpmode from being saved:</h2>

      <ul>
      <% @cpmode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-lg-4">
		  <div class="field">
		    <%= f.label @cpoint.caption %><br>
		  </div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-4">
		  <div class="field">
		    <%= f.label :date_reg %><br>
		    <%= f.date_select :date_reg, class:"form-control" %>
		  </div>
	  </div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-4">
		  <div class="field">
		    <%= f.label :value_min %><br>
		    <%= f.number_field :value_min, id: "sl_min_val", in: 0..10, step: 0.1, class: "form-control" %>
		    <%= f.range_field :value_min, id: "sl_min", in: 0..10, step: 0.1, class:"slide"%>
		    </div>
	    </div>
		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-4">
		  <div class="field">
		    <%= f.label :value_max %><br>
		    <%= f.number_field :value_max, id: "sl_max_val", in: 1..11, step: 0.1,class: "form-control" %>
		    <%= f.range_field :value_max, id: "sl_max", in: 1..11, step: 0.1, class:"slide"%>
		  </div>
	  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>
</div>

app/views/cpmodes/edit.html.erb
<div class="page-header">
<div class="container" style="background:cyan">
<div class="row">
	<div class="col-xs-12 col-sm-8 col-lg-6">
<h2>Editing Cpmode for <%=@cpoint.caption%></h2>
</div>
<ul class="list-inline pull-right">
<li><%= link_to 'Show', cpoint_cpmode_path( @cpoint, @cpmode ), class: "btn btn-success" %> </li>
<li><%= link_to 'Back', cpoint_cpmodes_path(@cpoint), class: "btn btn-default" %></li>
</ul>
											 </div>
											 </div>
</div>

<%= render 'form' %>

app/views/cpmodes/index.html.erb
<div class="page-header">
<ul class="list-inline pull-right">
<li> <%= link_to 'New Cpmode', new_cpoint_cpmode_path, class: "btn btn-success" %></li>
<li> <%= link_to "Cpoint", cpoint_path( @cpoint ), class: "btn btn-default" %></li>
<li> <%= link_to "All cpoints", cpoints_path( anchor: 'scroll'), class: "btn btn-default" %></li>

</ul>

<h3><%= @cpoint.caption %></h3>
<h4>Modes</h4>
</div>

<% if notice %>
	<div class="alert alert-info">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>


<table class="table table-bordered table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Date reg</th>
      <th>Value min</th>
      <th>Value max</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cpmodes.each do |cpmode| %>
      <tr>
        <td><%= cpmode.date_reg %></td>
        <td><%= cpmode.value_min %></td>
        <td><%= cpmode.value_max %></td>
        <td>
		<ul class="list-inline">
		<li><%= link_to 'Show', cpoint_cpmode_path( @cpoint, cpmode ), class: "btn btn-success" %></li>
		<li> <%= link_to 'Edit', edit_cpoint_cpmode_path(@cpoint, cpmode), class: "btn btn-warning" %></li>
        <li><%= link_to 'Destroy', [ @cpoint, cpmode ], method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger"%></li>
	</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cpmodes/new.html.erb
<h1>New Cpmode</h1>

<%= render 'form' %>

<%= link_to 'Back', cpoint_cpmodes_path(@cpoint) %>

app/views/cpmodes/show.html.erb
<% if notice %>
	<div class="alert alert-info">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>
<div class="page-header">
<div class="container" style="background:cyan">
<div class="row">
	<div class="col-xs-12 col-sm-8 col-lg-4">
	<h2>Control point mode</h2>
</div>
	<ul class="list-inline pull-right">
		<li><%= link_to 'Edit', edit_cpoint_cpmode_path(@cpoint, @cpmode), class: "btn btn-warning" %></li> 
		<li><%= link_to 'Back', cpoint_cpmodes_path(@cpoint), class: "btn btn-default" %></li>
											 </ul>
											 </div>
											 </div>
</div>
<div class="container" style="background:lightgrey">
<div class="row">
	<div class="col-xs-6" style="background:lightgreen">
	  <strong>Cpoint:</strong>
	  </div>
	  <div class="col-xs-6" style="background:white">
		  <%= @cpoint.caption %>
	  </div>
</div>

<div class="row">
	<div class="col-xs-6" style="background:aqua">
  <strong>Date reg:</strong>
	  </div>
	  <div class="col-xs-6" style="background:lightgrey">
  <%= @cpmode.date_reg %>
	  </div>
</div>

<div class="row">
	<div class="col-xs-6" style="background:aqua">
  <strong>Value range:</strong>
	  </div>
	  <div class="col-xs-6" style="font-weight: bold; background:lightgrey">
  <%= @cpmode.value_min %> -
  <%= @cpmode.value_max %>
	  </div>
</div>
</div>