config/routes.rb
Rails.application.routes.draw do

  get 'last/cpmodes'

	get 'cpoints/last_modes' => 'cpoints#last_modes'

  resources :cpoints do
					resources :cpmodes
  end

	namespace :last do
		resources :cpmodes
	end
end

app/models/cpoint.rb
class Cpoint < ActiveRecord::Base
	has_many :cpmodes
end

app/controllers/cpoints_controller.rb
class CpointsController < ApplicationController
  before_action :set_cpoint, only: [:show, :edit, :update, :destroy]

  # GET /cpoints
  # GET /cpoints.json
  def index
    @cpoints = Cpoint.all
  end

  # GET /cpoints/1
  # GET /cpoints/1.json
  def show
  end

	def last_modes
		modes = @cpoint.all
    respond_to do |format|
			render status: 200, json: {
							message: "Last modes",
							modes: modes
			}.to_json
		end
	end

  # GET /cpoints/new
  def new
    @cpoint = Cpoint.new
  end

  # GET /cpoints/1/edit
  def edit
  end

  # POST /cpoints
  # POST /cpoints.json
  def create
    @cpoint = Cpoint.new(cpoint_params)

    respond_to do |format|
      if @cpoint.save
        format.html { redirect_to @cpoint, notice: 'Cpoint was successfully created.' }
        format.json { render :show, status: :created, location: @cpoint }
      else
        format.html { render :new }
        format.json { render json: @cpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cpoints/1
  # PATCH/PUT /cpoints/1.json
  def update
    respond_to do |format|
      if @cpoint.update(cpoint_params)
	write_modes_image()

        format.html { redirect_to @cpoint, notice: 'Cpoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @cpoint }
      else
        format.html { render :edit }
        format.json { render json: @cpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cpoints/1
  # DELETE /cpoints/1.json
  def destroy
    @cpoint.destroy
    respond_to do |format|
      format.html { redirect_to cpoints_url, notice: 'Cpoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  	def write_modes_image()
			
		end

    # Use callbacks to share common setup or constraints between actions.
    def set_cpoint
      @cpoint = Cpoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cpoint_params
      params.require(:cpoint).permit(:caption, :image, :description, :code)
    end
end

app/helpers/cpoints_helper.rb
module CpointsHelper
end

app/views/cpoints/_form.html.erb
<%= form_for(@cpoint) do |f| %>
  <% if @cpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cpoint.errors.count, "error") %> prohibited this cpoint from being saved:</h2>

      <ul>
      <% @cpoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="form-group">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="form-group">
    <%= f.label :image%><br>
    <%= f.text_field :image%>
  </div>
  <div class="form-group">
    <%= f.label :description%><br>
    <%= f.text_field :description%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>
</div>

app/views/cpoints/edit.html.erb
<div class="page-header">
	<ul class="list-inline">
		<li><%= link_to 'Show', @cpoint, class:"btn btn-default" %></li>
		<li><%= link_to 'Back', cpoints_path, class:"btn btn-default" %></li>
	</ul>
</div>

<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
<h1>Editing Cpoint</h1>
		<%= render 'form' %>
	</div>
</div>	

app/views/cpoints/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
<%= link_to 'New Cpoint', new_cpoint_path, class: "btn btn-success pull-right" %>
<h1>Listing Cpoints<br> <small>for mode editor</small></h1>
</div>
<div class="row">
	<% @cpoints.each do |cpoint| %>
	<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
<table class="table table-bordered table-striped table-hover table-condensed">
<tr style="margin-left:auto;margin-right:auto;display:block;"><td style="margin-left:auto;margin-right:auto;" >
		<h2><%= cpoint.caption %></h2> <small style="text-align:right;"><%= cpoint.code.ceil.to_s unless cpoint.code.nil? %></small>
		<img class="img-responsive" src=<%=asset_path cpoint.image%>/>
		<p><%= cpoint.description %></p>
		<%= link_to 'Show', cpoint, class: "btn btn-primary" %>
		<%= link_to 'Edit', edit_cpoint_path(cpoint), class: "btn btn-success" %>
		<%= link_to 'Modes', cpoint_cpmodes_path(cpoint), class:"btn btn-default" %>
</td></tr>
		</table>
	</div>
	<% end %>
	<hr>
	<br><br>
	<h3>Control points</h3>
<table class="table table-stripped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Caption</th>
      <th>Image</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cpoints.each do |cpoint| %>
      <tr>
        <td><%= cpoint.caption %></td>
        <td><%= cpoint.image %></td>
        <td><%= cpoint.description%></td>
        <td><%= link_to 'Show', cpoint, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_cpoint_path(cpoint), class: "btn btn-success" %>
        <td><%= link_to 'Destroy', cpoint, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/cpoints/new.html.erb
<h1>New Cpoint</h1>

<%= render 'form' %>

<%= link_to 'Back', cpoints_path %>

app/views/cpoints/show.html.erb
<div class="page-header">
	<ul class="list-inline pull-right">
		<li><%= link_to 'Edit', edit_cpoint_path(@cpoint), class:"btn btn-warning" %></li>
		<li><%= link_to 'Back', cpoints_path, class:"btn btn-default" %></li>
		<li><%= link_to 'Modes', cpoint_cpmodes_path(@cpoint), class:"btn btn-default" %></li>
	</ul>
	<h3><%= @cpoint.caption %></h3>
</div>

<% if notice %>
	<div class="alert alert-info">
		<p id="notice"><%= notice %></p>
	</div>
<% end %>

<table class="table table-bordered">
	<tr>
		<td><strong>Caption:</strong></td>
		<td><%= @cpoint.caption %></td>
	</tr>
	<tr>
		<td>Modes image:</td>
		<td><%= @cpoint.image %></td>
		<td><img class="img-responsive" src=<%=asset_path @cpoint.image%>/></td>
	</tr>
	<tr>
		<td>Description:</td>
		<td><%= @cpoint.description %></td>
	</tr>

</table>